
services:
  cli:
    container_name: tsqm-php-cli
    image: tsqm-php-cli:latest
    build:
        context: .
    volumes:
        - ./:/tsqm-php
        - dot-ssh:/root/.ssh
  db:
    container_name: tsqm-php-db
    image: mysql:8
    platform: linux/x86_64
    ports:
        - 3306:3306
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: tsqm

volumes:
    logs:
    dot-ssh:
