
services:
  cli:
    container_name: tsqm-php-cli
    image: tsqm-php-cli:latest
    build:
        context: ${PWD}
    volumes:
        - ./:/tsqm-php
        - ssh-keys:/root/.ssh
  db:
    container_name: tsqm-php-db
    image: mysql:8
    platform: linux/x86_64
    ports:
        - 3306:3306
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: tsqm

volumes:
    logs:
    ssh-keys:
        driver: local
        driver_opts:
            type: none
            device: ${HOME}/.ssh/tsqm-php
            o: bind
