
services:
  cli:
    container_name: tsqm-php-cli
    image: tsqm-php-cli:latest
    build:
        context: ${PWD}
    volumes:
        - ./:/tsqm-php
        - ssh-keys:/root/.ssh

volumes:
    logs:
    ssh-keys:
        driver: local
        driver_opts:
            type: none
            device: ${HOME}/.ssh/tsqm-php
            o: bind
