name: CI
on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]    
    
permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-20.04

    steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
    
    - uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run test suite
      run: composer test

  lint-analyse:

    runs-on: ubuntu-20.04

    steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
    
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Lint PSR-12
      run: composer lint

    - name: Static analysis
      run: composer analyse
